I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 67, in script call
    call define_inventory
  File "game/script.rpy", line 67, in script call
    call define_inventory
ScriptError: could not find label 'define_inventory'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 67, in script call
    call define_inventory
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\ast.py", line 1313, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 67, in script call
    call define_inventory
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\script.py", line 843, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'define_inventory'.

Windows-8-6.2.9200
Ren'Py 6.99.11.1749
Apothecary Game 0.1
