I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/apothecary.rpy", line 10, in script call
    call calendar_ani(1)
  File "game/apothecary.rpy", line 10, in script call
    call calendar_ani(1)
ScriptError: could not find label 'calendar_ani'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/apothecary.rpy", line 10, in script call
    call calendar_ani(1)
  File "E:\_RenPy\renpy-6.99.12.2-sdk\renpy\ast.py", line 1322, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/apothecary.rpy", line 10, in script call
    call calendar_ani(1)
  File "E:\_RenPy\renpy-6.99.12.2-sdk\renpy\script.py", line 857, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'calendar_ani'.

Windows-8-6.2.9200
Ren'Py 6.99.12.2.2029
Apothecary Game 0.1
